#!/bin/bash
SESSION="servers"
MINECRAFT_WND="minecraft"
DSTARVE_WND="dontstarve"

MINECRAFT_DIR="/home/tenebrion/Minecraft/Old World"
MINECRAFT_CMD="$MINECRAFT_DIR/ServerStart.sh"

DSTARVE_DIR="/home/steam"
DSTARVE_CMD="$DSTARVE_DIR/start_dst.sh"

RETURN_STATUS=0

checkTmuxSession() 
{
    tmux has-session -t $SESSION > /dev/null 2>&1
    let RETURN_STATUS=$?
}

initTmux ()
{
    checkTmuxSession
    if [ $RETURN_STATUS -eq 1 ]
    then
        local OLD_PWD=$PWD
        # Change directory to where we want to land in the first window
        # Rename the window to something useful
        cd "$MINECRAFT_DIR" 
        tmux new-session -d -s $1 
        tmux rename-window -t0 $2

        # Change directory to where we want to land in the second window
        # Create the window with a useful name
        cd "$DSTARVE_DIR"
        tmux new-window -d -n $3
        cd $OLD_PWD 

        echo "Created tmux session"
    else
        echo "Tmux session already running"
    fi
}

checkMinecraftRunning ()
{
    pgrep java
    let RETURN_STATUS=$?
}

startMinecraft ()
{
    checkTmuxSession

    if [ $RETURN_STATUS -eq 1 ]
    then
        echo "No session found. Try servers setup."
        exit 1
    fi

    checkMinecraftRunning

    if [ $RETURN_STATUS -eq 1 ] 
    then
        tmux send-keys -t $SESSION:$MINECRAFT_WND "$MINECRAFT_CMD" Enter
        echo "Starting minecraft..."
    else
        echo "Minecraft is already running"
    fi
}

stopMinecraft ()
{
    checkMinecraftRunning

    if [ $RETRUN_STATUS -eq 0 ]
    then
        tmux send-keys -t $SESSION:$MINECRAFT_WND "stop" Enter
        echo "Stopping minecraft server..."
    else
        echo "No minecraft server running"
    fi
}

    startDontstarve ()
    {
        # I don't know how to check if this is running with any certainty
        tmux send-keys -t $SESSION:$DSTARVE_WND "$DSTARVE_CMD" Enter
        echo "Starting Don't starve together..."
    }

    startServer ()
    {
        case $1 in
            "$MINECRAFT_WND")
                startMinecraft
                ;;
            "$DSTARVE_WND")
                startDontstarve
                ;;
            "all")
                startMinecraft
                startDontstarve
                ;;
            *)
                echo "Unknown server $1"
                exit 1
                ;;
        esac
    }

    attachSession ()
    {
        case $1 in
            "$MINECRAFT_WND")
                tmux select-window -t $SESSION:$MINECRAFT_WND && tmux attach -t $SESSION
                ;;
            "$DSTARVE_WND")
                tmux select-window -t $SESSION:$DSTARVE_WND && tmux attach -t $SESSION
                ;;
            *)
                tmux select-window -t $SESSION:$MINECRAFT_WND && tmux attach -t $SESSION
                ;;
        esac
    }

    case $1 in
        "setup")
            initTmux $SESSION $MINECRAFT_WND $DSTARVE_WND
            ;;
        "start")
            startServer $2
            ;; 
        "attach")
            attachSession $2
            ;;
        "help")
            cat README.md
            ;;
        *)
            echo "Unknown action $1"
            exit 1
    esac
