#!/bin/bash
SESSION="servers"
MINECRAFT_WND="minecraft"
DSTARVE_WND="dontstarve"

MINECRAFT_DIR="/home/tenebrion/Minecraft/Old World"
MINECRAFT_CMD="cat ./ServerStart.sh"

DSTARVE_DIR="/home/steam"
DSTARVE_CMD="./start_dst.sh"

initTmux ()
{
    local OLD_PWD=$PWD
    # Change directory to where we want to land in the first window
    # Rename the window to something useful
    cd "$MINECRAFT_DIR" 
    tmux new-session -d -s $1 
    tmux rename-window -t0 $2

    # Change directory to where we want to land in the second window
    # Create the window with a useful name
    cd "$DSTARVE_DIR"
    tmux new-window -d -n $3
    cd $OLD_PWD 

    echo "Created tmux session"
}

startMinecraft ()
{
    tmux send-keys -t $SESSION:$MINECRAFT_WND "$MINECRAFT_CMD" Enter
    echo "Starting minecraft..."
}

startDontstarve ()
{
    tmux send-keys -t $SESSION:$DSTARVE_WND "$DSTARVE_CMD" Enter
    echo "Starting Don't starve together..."
}

startServer ()
{
    case $1 in
        "$MINECRAFT_WND")
            startMinecraft
            ;;
        "$DSTARVE_WND")
            startDontstarve
            ;;
        "all")
            startMinecraft
            startDontstarve
            ;;
        *)
            echo "Unknown server $1"
            exit 1
            ;;
    esac
}

attachSession ()
{
    case $1 in
        "$MINECRAFT_WND")
            tmux select-window -t $SESSION:$MINECRAFT_WND && tmux attach -t $SESSION
            ;;
        "$DSTARVE_WND")
            tmux select-window -t $SESSION:$DSTARVE_WND && tmux attach -t $SESSION
            ;;
        *)
            tmux select-window -t $SESSION:$MINECRAFT_WND && tmux attach -t $SESSION
            ;;
    esac
}

case $1 in
    "setup")
        initTmux $SESSION $MINECRAFT_WND $DSTARVE_WND
        ;;
    "start")
        startServer $2
        ;; 
    "attach")
        attachSession $2
        ;;
    *)
        echo "Unknown action $1"
        exit 1
esac
